on: push
name: Main
jobs:
  batsTest:
    name: Bats Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bats Test
      uses: actions/bin/bats@master
      with:
        args: test/*.bats
  shellLint:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Shell Lint
      uses: actions/bin/shellcheck@master
      with:
        args: entrypoint.sh
  dockerLint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile

  dockerBuild:
    name: Docker Build
    needs: [shellLint, batsTest, dockerLint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Docker Build
      uses: actions/docker/cli@master
      with:
        args: build -t actions-yarn .
